-- Run this entire file in Supabase SQL Editor.
create table if not exists public.course_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_slug text not null default 'turning-forward',
  progress jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, course_slug)
);

alter table public.course_progress enable row level security;

drop policy if exists "Students read own progress" on public.course_progress;
create policy "Students read own progress" on public.course_progress for select using (auth.uid() = user_id);

drop policy if exists "Students insert own progress" on public.course_progress;
create policy "Students insert own progress" on public.course_progress for insert with check (auth.uid() = user_id);

drop policy if exists "Students update own progress" on public.course_progress;
create policy "Students update own progress" on public.course_progress for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists course_progress_user_id_idx on public.course_progress(user_id);
