"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import Header from "@/components/Header";
import { useAuth } from "@/components/AuthProvider";
import { loadCloudProgress, loadLocalProgress, saveCloudProgress, saveLocalProgress, ProgressData } from "@/lib/progress";

const tabs=["Lesson 1","Lesson 2","Lesson 3","Challenge"] as const; type Tab=(typeof tabs)[number];
export default function ModulePage(){const params=useParams<{module:string}>(); if(params.module!=="module-1") return <main><Header/><section className="empty-state"><h1>This module is coming soon.</h1><Link className="button" href="/course/turning-forward">Return to course</Link></section></main>; return <ModuleOne/>}
function ModuleOne(){const [tab,setTab]=useState<Tab>("Lesson 1");const [saved,setSaved]=useState<ProgressData>({});const [ready,setReady]=useState(false);const [sync,setSync]=useState("Saved on this device");const {user,loading}=useAuth();
useEffect(()=>{if(loading)return;const local=loadLocalProgress();if(!user){setSaved(local);setReady(true);return;}loadCloudProgress(user.id).then(cloud=>setSaved({...local,...cloud})).catch(()=>setSaved(local)).finally(()=>setReady(true));},[user,loading]);
useEffect(()=>{if(!ready)return;saveLocalProgress(saved);if(!user){setSync("Saved on this device");return;}setSync("Saving…");const t=setTimeout(()=>saveCloudProgress(user.id,saved).then(()=>setSync("Saved to your account")).catch(()=>setSync("Cloud sync unavailable; saved locally")),500);return()=>clearTimeout(t)},[saved,user,ready]);
const completed=useMemo(()=>[saved.lesson1,saved.lesson2,saved.lesson3,saved.challenge].filter(Boolean).length,[saved]);const field=(k:string,v:string|boolean)=>setSaved(s=>({...s,[k]:v}));const finish=(k:string,next?:Tab)=>{field(k,true);if(next)setTab(next);window.scrollTo({top:0,behavior:"smooth"})};
return <main><Header/><section className="lesson-shell shell"><div className="lesson-top"><Link href="/course/turning-forward">← Course overview</Link><span>{completed} of 4 complete · {sync}</span></div><div className="module-banner"><span>MODULE 1</span><h1>The Decision to Turn Forward</h1><p>Identity, responsibility, fear, and the structure required to create momentum.</p></div><div className="tab-row">{tabs.map((t,i)=>{const key=["lesson1","lesson2","lesson3","challenge"][i];return <button key={t} className={tab===t?"selected":""} onClick={()=>setTab(t)}><b>{saved[key]?"✓":"○"}</b>{t}</button>})}</div>{tab==="Lesson 1"&&<LessonOne s={saved} f={field} done={()=>finish("lesson1","Lesson 2")}/>} {tab==="Lesson 2"&&<LessonTwo s={saved} f={field} done={()=>finish("lesson2","Lesson 3")}/>} {tab==="Lesson 3"&&<LessonThree s={saved} f={field} done={()=>finish("lesson3","Challenge")}/>} {tab==="Challenge"&&<Challenge s={saved} f={field} done={()=>finish("challenge")}/>}</section></main>}
function Video({title}:{title:string}){return <div className="video"><div className="play">▶</div><div><span>VIDEO LESSON</span><h3>{title}</h3><p>Replace this panel with a private Vimeo, Mux, or YouTube embed.</p></div></div>}
function Interaction({title,children}:{title:string,children:React.ReactNode}){return <section className="interaction"><h3>{title}</h3>{children}</section>}
function Quiz({items,s,f}:{items:[string,string,string[],string][],s:ProgressData,f:(k:string,v:string)=>void}){return <section className="quiz"><h3>Knowledge Check</h3>{items.map(([k,q,opts,a],i)=><div className="question" key={k}><strong>{i+1}. {q}</strong>{opts.map(o=><label className={`option ${s[k]===o?(o===a?"correct":"incorrect"):""}`} key={o}><input type="radio" name={k} checked={s[k]===o} onChange={()=>f(k,o)}/>{o}</label>)}</div>)}</section>}
function LessonOne({s,f,done}:{s:ProgressData,f:(k:string,v:string|boolean)=>void,done:()=>void}){const ok=String(s.waiting||"").length>2&&String(s.becoming||"").length>20&&["l1q1","l1q2","l1q3","l1q4"].every(k=>s[k]);return <article className="lesson-content"><span className="lesson-kicker">LESSON 1</span><h2>You Are Not Starting Over</h2><Video title="The Decision"/><h3>The myth of starting over</h3><p>Most people think they need a fresh start. But you do not need a reset—you need a decision. You are not blank, erased, or without history. You are experienced, shaped, and capable of using what you have learned.</p><blockquote>Turning forward is not denial. It is integration.</blockquote><h3>Identity versus reputation</h3><p>Reputation is what people think. Identity is what you decide. Rebuild identity first; reputation follows consistent action.</p><h3>Responsibility without shame</h3><p>Responsibility says, “That was me, that decision was mine, and now I move.” Shame says, “I am irredeemable.” Own your choices without destroying your worth.</p><Interaction title="Pause and complete the sentence"><label>I am no longer waiting for…<textarea value={String(s.waiting||"")} onChange={e=>f("waiting",e.target.value)}/></label></Interaction><Interaction title="Identity Rewrite"><label>Write at least five sentences beginning with “I am becoming…”<textarea className="large" value={String(s.becoming||"")} onChange={e=>f("becoming",e.target.value)}/></label></Interaction><Quiz s={s} f={(k,v)=>f(k,v)} items={[["l1q1","Turning forward means:",["Erasing your history","Integrating experience and moving deliberately"],"Integrating experience and moving deliberately"],["l1q2","Turning forward requires erasing the past.",["True","False"],"False"],["l1q3","What should be rebuilt first?",["Reputation","Identity"],"Identity"],["l1q4","Responsibility without shame is:",["Avoiding accountability","Ownership without self-destruction"],"Ownership without self-destruction"]]}/><button className="button full" disabled={!ok} onClick={done}>Complete Lesson 1 →</button></article>}
function LessonTwo({s,f,done}:{s:ProgressData,f:(k:string,v:string|boolean)=>void,done:()=>void}){const fields=["fear","think","worst","likely","action"];const ok=fields.every(k=>String(s[k]||"").length>2)&&["l2q1","l2q2","l2q3"].every(k=>s[k]);return <article className="lesson-content"><span className="lesson-kicker">LESSON 2</span><h2>Fear Is Information, Not Instruction</h2><Video title="Moving While Afraid"/><p>Fear often appears the moment you attempt to grow. It may tell you something is unfamiliar, important, or stretching you—but fear does not get to vote.</p><blockquote>Fear is information. Avoidance is the real enemy.</blockquote><h3>Survival mode versus strategy mode</h3><p>Survival mode reacts. Strategy mode pauses, evaluates, plans, and moves deliberately. The goal is not to stop feeling fear; it is to stop allowing fear to make every decision.</p><Interaction title="Fear Mapping Tool">{[["fear","Current fear"],["think","What I think will happen"],["worst","Worst-case scenario"],["likely","Most likely scenario"],["action","One forward action I can take this week"]].map(([k,l])=><label key={k}>{l}<textarea value={String(s[k]||"")} onChange={e=>f(k,e.target.value)}/></label>)}</Interaction><Quiz s={s} f={(k,v)=>f(k,v)} items={[["l2q1","Fear is:",["A stop sign","A signal"],"A signal"],["l2q2","Survival mode is primarily:",["Reactive","Strategic"],"Reactive"],["l2q3","Scarcity thinking affects:",["Only confidence","Both confidence and decisions"],"Both confidence and decisions"]]}/><button className="button full" disabled={!ok} onClick={done}>Complete Lesson 2 →</button></article>}
function LessonThree({s,f,done}:{s:ProgressData,f:(k:string,v:string|boolean)=>void,done:()=>void}){const ok=["wake","nonnegotiables","growth","eliminate"].every(k=>String(s[k]||"").length>2);return <article className="lesson-content"><span className="lesson-kicker">LESSON 3</span><h2>The First Discipline: Structure</h2><Video title="Systems Create Stability"/><p>Motivation is unreliable. Discipline builds momentum. Freedom without structure can feel unstable, but structure creates safety, safety creates clarity, and clarity makes progress possible.</p><blockquote>You cannot out-motivate chaos. You must out-structure it.</blockquote><h3>Micro-commitments</h3><p>Choose small, repeatable behaviors: a wake time, a study block, a savings percentage, ten pages of reading, or a scheduled workout. Momentum is built in inches.</p><Interaction title="Structure Builder">{[["wake","My wake time"],["nonnegotiables","My three non-negotiables"],["growth","My growth block: time and activity"],["eliminate","One habit I am eliminating"]].map(([k,l])=><label key={k}>{l}<textarea value={String(s[k]||"")} onChange={e=>f(k,e.target.value)}/></label>)}</Interaction><button className="button full" disabled={!ok} onClick={done}>Complete Lesson 3 →</button></article>}
function Challenge({s,f,done}:{s:ProgressData,f:(k:string,v:string|boolean)=>void,done:()=>void}){const ok=["routine","fearAction","identityBehavior"].every(k=>String(s[k]||"").length>2)&&Boolean(s.pledge);return <article className="lesson-content"><span className="lesson-kicker">WEEKLY FORWARD CHALLENGE</span><h2>Turn the Decision into Action</h2><p>Choose one behavior in each category. Keep it realistic, measurable, and specific enough to complete within seven days.</p><Interaction title="My commitments">{[["routine","One structured daily routine"],["fearAction","One fear-facing action"],["identityBehavior","One identity-building behavior"]].map(([k,l])=><label key={k}>{l}<textarea value={String(s[k]||"")} onChange={e=>f(k,e.target.value)}/></label>)}<label className="check"><input type="checkbox" checked={Boolean(s.pledge)} onChange={e=>f("pledge",e.target.checked)}/> I commit to completing these actions during the next seven days.</label></Interaction>{s.challenge?<div className="completion"><b>✓</b><h3>Module 1 complete</h3><p>You made the decision. Forward is not loud—it is consistent.</p><Link className="button secondary" href="/course/turning-forward">Return to course</Link></div>:<button className="button full" disabled={!ok} onClick={done}>I Commit to Turning Forward</button>}</article>}
